[server]
bind = ":8080"
path = "/bbs"
ws = "/ws"

[bbs]
name = "limbo test board"
desc = "\"next-generation message board\""

[database]
addr = "localhost" # uses default mongodb port
name = "limbo"

[webclient]
index = "/Users/greg/code/bbs-client/index.html"
static = "/Users/greg/code/bbs-client/static"